import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="md:w-[300px]">
          <div className="px-4 flex items-center justify-between">
            <Link href="/">
              <h1 className="text-xl hover:text-rose-500">Pokérrombados</h1>
            </Link>
            <Link href="/results">
              <h1 className="text-md hover:text-rose-500">resultados</h1>
            </Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
